### PR TITLE
feature: Add Form Extension

### PR DESCRIPTION
**Pull request by kjohnson**
## Description

This PR adds a form extension for v3 compatibility.

Related: 
[Refactor: ActiveCampaign has block requirements #5 
](https://github.com/impress-org/give-activecampaign/pull/5)
[Refactor: block design improvements #6](https://github.com/impress-org/give-activecampaign/pull/6)

## Visuals

image

## Testing Instructions

- Add API URL and API Key
- Create a  v3 form
- Add an ActiveCampaign opt-in field

### CODE REVIEW

**Review by alaca — APPROVED** [review]
Looks good :+1:

**Comment by kjohnson** [comment]
Build: https://github.com/impress-org/give-activecampaign/actions/runs/7134335620

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
